export const masterDataDefaults = {
  identity: {
    fullName: 'Rahul Sharma',
    mobile: '+91 98765 43210',
    email: 'rahul.sharma@email.com',
    dob: '1998-05-15',
    gender: 'Male',
    city: 'Bengaluru',
    state: 'Karnataka',
    employmentType: 'Salaried',
    dependents: '0',
    maritalStatus: 'Single',
    pan: 'ABCDE1234F',
    employer: 'TechCorp India',
    department: 'Engineering',
    designation: 'Software Engineer',
  },
  income: {
    monthlyActiveIncome: '100000',
    incomeFrequency: 'Monthly',
    hasPassiveIncome: true,
    passiveIncomeAmount: '25000',
    passiveIncomeSource: 'Dividends & Interest',
    salaryBreakup: 'Basic: 40k, HRA: 20k, Special: 40k',
  },
  expenses: {
    monthlyFixedExpenses: '42000',
    monthlyVariableExpenses: '26000',
    totalEmi: '25000',
    activeLoans: '1',
    monthlySavings: '10000',
    loanDetails: 'Home Loan: 25k EMI',
    expenseCategoryBreakdown: 'Rent: 25k, Food: 15k, Travel: 10k',
  },
  savings: {
    hasEmergencyFund: true,
    emergencyFundRange: '1-3L',
    emergencyFundParked: 'Savings Account',
  },
  insurance: {
    hasHealthInsurance: true,
    healthCover: '500000',
    isFamilyCovered: false,
    hasLifeInsurance: true,
    lifeCover: '5000000',
    hasTermPlan: true,
    termCover: '5000000',
    insurerName: 'HDFC Life / Niva Bupa',
    policyNumber: 'POL12345678',
    policyExpiry: '2027-01-01',
    hasCriticalIllness: false,
    hasAccidentalCover: true,
  },
  investment: {
    doesInvest: true,
    investmentTypes: 'Mutual Funds, Stocks',
    monthlyInvestment: '15000',
    riskAppetite: 'Moderate',
    primaryInvestmentGoal: 'Retirement',
    existingPortfolio: '920000',
    equityExposurePct: '60',
    totalInvested: '750000',
  },
}

export const masterDataTabs = [
  { id: 'identity', label: 'Identity' },
  { id: 'income', label: 'Income' },
  { id: 'expenses', label: 'Expenses' },
  { id: 'savings', label: 'Savings' },
  { id: 'insurance', label: 'Insurance' },
  { id: 'investment', label: 'Investment' },
]

export const fieldLabels = {
  fullName: 'Full Name',
  mobile: 'Mobile Number',
  email: 'Email',
  dob: 'Date of Birth',
  gender: 'Gender',
  city: 'City',
  state: 'State',
  employmentType: 'Employment Type',
  dependents: 'Dependents',
  maritalStatus: 'Marital Status',
  pan: 'PAN',
  employer: 'Employer',
  department: 'Department',
  designation: 'Designation',
  monthlyActiveIncome: 'Monthly Active Income (₹)',
  incomeFrequency: 'Income Frequency',
  hasPassiveIncome: 'Has Passive Income?',
  passiveIncomeAmount: 'Passive Income Amount (₹)',
  passiveIncomeSource: 'Passive Income Source',
  salaryBreakup: 'Salary Breakup',
  monthlyFixedExpenses: 'Monthly Fixed Expenses (₹)',
  monthlyVariableExpenses: 'Monthly Variable Expenses (₹)',
  totalEmi: 'Total EMI (₹)',
  activeLoans: 'Active Loans',
  monthlySavings: 'Monthly Savings (₹)',
  loanDetails: 'Loan Details',
  expenseCategoryBreakdown: 'Expense Category Breakdown',
  hasEmergencyFund: 'Has Emergency Fund?',
  emergencyFundRange: 'Emergency Fund Range',
  emergencyFundParked: 'Where is it parked?',
  hasHealthInsurance: 'Has Health Insurance?',
  healthCover: 'Health Cover (₹)',
  isFamilyCovered: 'Is Family Covered?',
  hasLifeInsurance: 'Has Life Insurance?',
  lifeCover: 'Life Cover (₹)',
  hasTermPlan: 'Has Term Plan?',
  termCover: 'Term Cover (₹)',
  insurerName: 'Insurer Name',
  policyNumber: 'Policy Number',
  policyExpiry: 'Policy Expiry Date',
  hasCriticalIllness: 'Has Critical Illness Cover?',
  hasAccidentalCover: 'Has Accidental Cover?',
  doesInvest: 'Do you invest?',
  investmentTypes: 'Investment Types',
  monthlyInvestment: 'Monthly Investment (₹)',
  riskAppetite: 'Risk Appetite',
  primaryInvestmentGoal: 'Primary Investment Goal',
  existingPortfolio: 'Existing Portfolio Value (₹)',
  equityExposurePct: 'Equity Exposure (%)',
  totalInvested: 'Total Invested Amount (₹)',
}
