export const masterDataDefaults = {
  identity: {
    fullName: 'Rahul Sharma',
    age: '28',
    gender: 'Male',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560001',
    email: 'rahul.sharma@email.com',
    phone: '+91 98765 43210',
    maritalStatus: 'Single',
    dependents: '0',
    occupation: 'Software Engineer',
    employer: 'TechCorp India',
  },
  income: {
    activeMonthly: '100000',
    passiveMonthly: '25000',
    bonusAnnual: '200000',
    rentalIncome: '0',
    dividendIncome: '8000',
    freelanceIncome: '15000',
    otherIncome: '2000',
    incomeStability: 'High',
    nextReviewDate: '2026-12-01',
  },
  expenses: {
    rentEmi: '25000',
    utilities: '4500',
    groceries: '12000',
    dining: '8000',
    transport: '5000',
    subscriptions: '2500',
    entertainment: '4000',
    healthcare: '2000',
    education: '0',
    insurancePremiums: '3500',
    otherFixed: '5000',
    otherFlexible: '6500',
  },
  savings: {
    emergencyFund: '185000',
    bankSavings: '45000',
    liquidFunds: '80000',
    shortTermGoals: '60000',
    targetMonths: '6',
    monthlySavingsGoal: '20000',
    autoSweep: 'Yes',
  },
  insurance: {
    termCover: '5000000',
    termPremium: '850',
    termInsurer: 'HDFC Life',
    healthCover: '500000',
    healthPremium: '1200',
    healthInsurer: 'Niva Bupa',
    criticalIllness: '0',
    accidentCover: '1000000',
    employerCover: '300000',
  },
  investment: {
    equityMutualFunds: '420000',
    stocks: '132000',
    debtFunds: '180000',
    ppf: '96000',
    epf: '210000',
    gold: '92000',
    realEstate: '0',
    crypto: '0',
    monthlySip: '15000',
    riskProfile: 'Moderate',
    horizonYears: '15',
  },
}

export const masterDataTabs = [
  { id: 'identity', label: 'Identity' },
  { id: 'income', label: 'Income' },
  { id: 'expenses', label: 'Expenses' },
  { id: 'savings', label: 'Savings' },
  { id: 'insurance', label: 'Insurance' },
  { id: 'investment', label: 'Investment' },
]

export const fieldLabels = {
  fullName: 'Full Name',
  age: 'Age',
  gender: 'Gender',
  city: 'City',
  state: 'State',
  pincode: 'Pincode',
  email: 'Email',
  phone: 'Phone',
  maritalStatus: 'Marital Status',
  dependents: 'Dependents',
  occupation: 'Occupation',
  employer: 'Employer',
  activeMonthly: 'Active Monthly Income (₹)',
  passiveMonthly: 'Passive Monthly Income (₹)',
  bonusAnnual: 'Annual Bonus (₹)',
  rentalIncome: 'Rental Income (₹)',
  dividendIncome: 'Dividend Income (₹)',
  freelanceIncome: 'Freelance Income (₹)',
  otherIncome: 'Other Income (₹)',
  incomeStability: 'Income Stability',
  nextReviewDate: 'Next Review Date',
  rentEmi: 'Rent / EMI (₹)',
  utilities: 'Utilities (₹)',
  groceries: 'Groceries (₹)',
  dining: 'Dining (₹)',
  transport: 'Transport (₹)',
  subscriptions: 'Subscriptions (₹)',
  entertainment: 'Entertainment (₹)',
  healthcare: 'Healthcare (₹)',
  education: 'Education (₹)',
  insurancePremiums: 'Insurance Premiums (₹)',
  otherFixed: 'Other Fixed (₹)',
  otherFlexible: 'Other Flexible (₹)',
  emergencyFund: 'Emergency Fund (₹)',
  bankSavings: 'Bank Savings (₹)',
  liquidFunds: 'Liquid Funds (₹)',
  shortTermGoals: 'Short-term Goals (₹)',
  targetMonths: 'Target Months Cover',
  monthlySavingsGoal: 'Monthly Savings Goal (₹)',
  autoSweep: 'Auto Sweep Enabled',
  termCover: 'Term Cover (₹)',
  termPremium: 'Term Premium / mo (₹)',
  termInsurer: 'Term Insurer',
  healthCover: 'Health Cover (₹)',
  healthPremium: 'Health Premium / mo (₹)',
  healthInsurer: 'Health Insurer',
  criticalIllness: 'Critical Illness Cover (₹)',
  accidentCover: 'Accident Cover (₹)',
  employerCover: 'Employer Cover (₹)',
  equityMutualFunds: 'Equity Mutual Funds (₹)',
  stocks: 'Direct Stocks (₹)',
  debtFunds: 'Debt Funds (₹)',
  ppf: 'PPF (₹)',
  epf: 'EPF (₹)',
  gold: 'Gold (₹)',
  realEstate: 'Real Estate (₹)',
  crypto: 'Crypto (₹)',
  monthlySip: 'Monthly SIP (₹)',
  riskProfile: 'Risk Profile',
  horizonYears: 'Investment Horizon (years)',
}
