export const weeklyInitialData = {
  weeks: [
    {
      id: 1,
      label: 'Week 1',
      range: '1 Jul – 7 Jul 2026',
      score: 68,
      income: 28000,
      observation: 'Dining out exceeded safe band twice. Groceries stayed optimal.',
      logged: { groceries: 4200, dining: 3800, transport: 1600 },
      heatmap: ['optimal', 'optimal', 'safe', 'missed', 'optimal', 'safe', 'optimal'],
    },
    {
      id: 2,
      label: 'Week 2',
      range: '8 Jul – 14 Jul 2026',
      score: 74,
      income: 28000,
      observation: 'Transport costs dipped. Good control on discretionary spend.',
      logged: { groceries: 3900, dining: 2200, transport: 1200 },
      heatmap: ['optimal', 'safe', 'optimal', 'optimal', 'safe', 'optimal', 'optimal'],
    },
    {
      id: 3,
      label: 'Week 3',
      range: '15 Jul – 21 Jul 2026',
      score: 61,
      income: 27500,
      observation: 'Weekend dining spike pulled you into missed band.',
      logged: { groceries: 4500, dining: 5100, transport: 1800 },
      heatmap: ['safe', 'optimal', 'missed', 'missed', 'safe', 'optimal', 'safe'],
    },
    {
      id: 4,
      label: 'Week 4',
      range: '22 Jul – 28 Jul 2026',
      score: 72,
      income: 30000,
      observation: 'Balanced week. Stay within dining max to protect your streak.',
      logged: { groceries: 4100, dining: 2500, transport: 1400 },
      heatmap: ['optimal', 'optimal', 'safe', 'optimal', 'safe', 'optimal', 'safe'],
    },
  ],
  targets: {
    groceries: { min: 3000, max: 4500 },
    dining: { min: 1500, max: 3000 },
    transport: { min: 800, max: 2000 },
  },
  streakWeeks: 4,
  currentWeekId: 4,
  dayLabels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
}
