export const weeklyInitialData = {
  weeks: [
    {
      id: 1,
      label: 'Week 1',
      range: '1 Jul – 7 Jul 2026',
      discipline_score: 68,
      income: 28000,
      observation: 'Flexible spend exceeded target. Savings maintained.',
      logged: { fixed_expenses: 12000, flexible_expenses: 6000, savings: 10000 },
      year: 2026,
      week_no: 27,
      heatmap: ['optimal', 'optimal', 'safe', 'missed', 'optimal', 'safe', 'optimal'],
    },
    {
      id: 2,
      label: 'Week 2',
      range: '8 Jul – 14 Jul 2026',
      discipline_score: 74,
      income: 28000,
      observation: 'Good control on flexible spend.',
      logged: { fixed_expenses: 12000, flexible_expenses: 4500, savings: 11500 },
      year: 2026,
      week_no: 28,
      heatmap: ['optimal', 'safe', 'optimal', 'optimal', 'safe', 'optimal', 'optimal'],
    },
    {
      id: 3,
      label: 'Week 3',
      range: '15 Jul – 21 Jul 2026',
      discipline_score: 61,
      income: 27500,
      observation: 'Weekend dining spike pulled you into missed band.',
      logged: { fixed_expenses: 12000, flexible_expenses: 9000, savings: 6500 },
      year: 2026,
      week_no: 29,
      heatmap: ['safe', 'optimal', 'missed', 'missed', 'safe', 'optimal', 'safe'],
    },
    {
      id: 4,
      label: 'Week 4',
      range: '22 Jul – 28 Jul 2026',
      discipline_score: 72,
      income: 30000,
      observation: 'Balanced week. Stay within limits to protect your streak.',
      logged: { fixed_expenses: 12000, flexible_expenses: 5000, savings: 13000 },
      year: 2026,
      week_no: 30,
      heatmap: ['optimal', 'optimal', 'safe', 'optimal', 'safe', 'optimal', 'safe'],
    },
  ],
  targets: {
    fixed: { min: 10000, max: 15000 },
    flexible: { min: 4000, max: 8000 },
    savings: { min: 8000, max: 12000 },
  },
  streakWeeks: 4,
  currentWeekId: 4,
  dayLabels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
}
